# The settings in this configuration takes precedence over ruff's default.
# See the default configuration at https://docs.astral.sh/ruff/configuration/

line-length = 120 # more than the default 88

# Python version to target
target-version = "py312"

[lint]
# Enable *all* rules, also the new ones after upgrading ruff
# See the rules at https://docs.astral.sh/ruff/rules/
select = ["ALL"]
# Every rule which is disabled and why it is...
ignore = [
	"D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", # Missing docstrings for module, class, and more...
	"D203", # Incompatible with D211, one has to be enabled and the other ignored
	"D212", # Incompatible with D213, one has to be enabled and the other ignored
	"ISC001", "COM812", # As recommended by ruff when running `ruff format`, these rules should be disabled to avoid unexpected behavior
]
